### ISSUE TITLE
Please add Alipay fingerprint payment support

### ISSUE THREAD

**Issue by ljkgpxs** [CyanogenMod/android_device_xiaomi_gemini#1]
Alipay fingerprint payment does not work on CM, please add this feature. Oneplus3 already complete this [function](https://github.com/CyanogenMod/android_device_oneplus_oneplus3/commit/95df6ed07d67ea563753c154c7d4eb8ceb113b64).

**Comment by bgcngm** [comment]
There's no way I can test that. I need someone experienced to do some testing, otherwise it's a no go.

**Comment by VvvvvGH** [comment]
I will be the volunteer.
I am using alipay and hope to use fingerprint .

**Comment by ljkgpxs** [comment]
Well...anyway, thanks for your reply!

**Comment by bgcngm** [comment]
@cheng-x and @ljkgpxs don't get me wrong. I have tried once to add AliPay, TaoBao and WeChat fingerprint support, by porting it from OnePlus3 and didn't work. When I mean someone experienced to do testing it's because I need logs to see if anything comes up. Are you still running cm-13.0?

**Comment by ljkgpxs** [comment]
@bgcngm Ya, I'm running CM-13.0. I think you donot use Alipay and have not tried porting it. I have tried to porting it from OP3 today, but did not test it. I have to backup data. So I will test it soon and give your result. If it did not work, you can give me your porting version, I will test it and give you the logs.

**Comment by bgcngm** [comment]
Of course I have tried to port it, on a request from a Chinese user that contacted me directly. Back then, it didn't work, but I didn't take a look at any logs. Maybe it's worth a shot.

**Comment by ljkgpxs** [comment]
@bgcngm I have test it. Something is wrong with ifaadaemon, Alipay app can show the fingerprint option, but when I touch the sensor, it always give me a verification failed.Here is my logcat. You can give me your porting version anytime, I will test it.
[logcat.txt](https://github.com/CyanogenMod/android_device_xiaomi_gemini/files/606022/logcat.txt)

**Comment by bgcngm** [comment]
> 11-22 17:38:32.990  5746  7884 I ifaadaemonClient: adapter_TEEClient_invokeCmd called
> 11-22 17:38:32.990  5746  7884 I ifaadaemonClient: invoke_command: input_buf len = 962
> 11-22 17:38:32.992  5746  7884 E         : BP zero length 962 4096
> 11-22 17:38:32.992  5746  7884 I         : sendCommand:bp transcat cmdlen 962 rspLen 4096
> 11-22 17:38:33.984  5746  7884 E         : Couldn't contact remote: -22
> 11-22 17:38:33.984  5746  7884 I ifaadaemonClient: after invoke_command :output_buf len = 4096
> 11-22 17:38:33.984  5746  7884 E ifaadaemonClient: TEEClient:OUT:FAIL..........ret=-22!=0 rbuf_len=4096<=0

I bet that ifaadaemon is tied to OnePlus3 tee client. Although I don't like the idea of kanging QSEE blobs, you can give it a try.

@dianlujitao, could you please try to help on this?

**Comment by VvvvvGH** [comment]
I am working on this as well.
I think we need to get the firmware files and .so files from latest china miui rom.
I don't think we can port wechat fingerprint.Because the offical miui doesn't  support it . 
@bgcngm @dianlujitao  

lib from MIUI
.plt:00000A30 ; ---------------------------------------------------------------------------
.plt:00000A30 ; File Name   : \miui\alipay\lib\libteeclientjni.so
.plt:00000A30 ; Format      : ELF for ARM (Shared object)
.plt:00000A30 ; Interpreter '/system/bin/linker'
.plt:00000A30 ; Needed Library 'libc.so'
.plt:00000A30 ; Needed Library 'libcutils.so'
.plt:00000A30 ; Needed Library 'libutils.so'
.plt:00000A30 ; Needed Library 'libQSEEComAPI.so'
.plt:00000A30 ; Needed Library 'libbinder.so'
.plt:00000A30 ; Needed Library 'libmlipay.so'
.plt:00000A30 ; Needed Library 'libc++.so'
.plt:00000A30 ; Needed Library 'libdl.so'
.plt:00000A30 ; Needed Library 'libm.so'
.plt:00000A30 ; Shared Name 'libteeclientjni.so'
.plt:00000A30 ;
.plt:00000A30 ; EABI version: 5
.plt:00000A30 ;




lib from OP3

.plt:000007F4 ; Format      : ELF for ARM (Shared object)
.plt:000007F4 ; Interpreter '/system/bin/linker'
.plt:000007F4 ; Needed Library 'libc.so'
.plt:000007F4 ; Needed Library 'libcutils.so'
.plt:000007F4 ; Needed Library 'libutils.so'
.plt:000007F4 ; Needed Library 'libQSEEComAPI.so'
.plt:000007F4 ; Needed Library 'libc++.so'
.plt:000007F4 ; Needed Library 'libdl.so'
.plt:000007F4 ; Needed Library 'libm.so'
.plt:000007F4 ; Shared Name 'libteeclientjni.so'

**Comment by bgcngm** [comment]
@cheng-x, so did you try with libteeclientjni.so from MIUI? When I tried to port this, I kanged [all alipay blobs (including firmware) from OnePlus3](https://github.com/CyanogenMod/android_device_oneplus_oneplus3/blob/cm-13.0/proprietary-files.txt#L1-L13). If you try to get those libs from MIUI, then be sure to fill in the needed dependencies (libmlipay.so for example). For the firmware in MIUI, this is stored here: /firmware/image/mlipay.*.

**Comment by VvvvvGH** [comment]
As I know.To port alipay fingerprint and pass the verification .Some files from miui is required.
However I have no idea in porting mlipay . 
Maybe we can use the  firmware from miui. 
I extracted the system img but I found nothing from /firmware/image/mlipay.*.
@bgcngm @ljkgpxs

**Comment by moetayuko** [comment]
IMO you can kang all op3 ifaa blobs except etc/firmware/alipay* @bgcngm

**Comment by zyhq** [comment]
Even if the extraction is successful, can only support Alipay, because MIUI doesn't support WeChat's fingerprint payment. @bgcngm @cheng-x

**Comment by bgcngm** [comment]
@zyhq, I think that OnePlus3 didn't support WeChat out-of-the-box as well (and its support was added later into CM). But first things first, let's try AliPay and then the rest can follow.

**Comment by bgcngm** [comment]
Any update on this?
